import Link from "next/link";

import { RetryButton } from "@/components/admin/retry-button";
import { AdminBackendError, getAdminLeads } from "@/lib/admin/backend";

function formatDate(value: string) { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)); }

export default async function AdminLeadsPage() {
  const result = await getAdminLeads({ limit: 50 }).then((value) => ({ value })).catch((error) => ({ error }));
  const data = "value" in result ? result.value : null;
  const loadError = "error" in result ? result.error : null;
  return <div className="mx-auto max-w-[1500px]"><div className="border-b border-ink/10 pb-9"><p className="eyebrow">Sales pipeline</p><h1 className="mt-3 font-serif text-5xl tracking-[-0.03em] sm:text-6xl">Leads.</h1><p className="mt-4 text-sm text-ink/50">Keep every studio enquiry visible from first contact to confirmed project.</p></div>{!data ? <div className="mt-8 border border-[#b36a60]/30 bg-[#b36a60]/10 p-7"><p className="eyebrow text-[#85483f]">Data unavailable</p><h2 className="mt-3 font-serif text-3xl">Lead data could not be loaded.</h2><p className="mt-3 text-sm text-ink/55">{loadError instanceof AdminBackendError && loadError.detail === "Admin API configuration is incomplete." ? "Add ADMIN_API_KEY to the frontend server environment." : "The studio connection did not respond."}</p><div className="mt-6"><RetryButton /></div></div> : data.items.length ? <div className="mt-8 overflow-x-auto border border-ink/10 bg-paper"><table className="w-full min-w-[900px] border-collapse text-left"><thead><tr className="border-b border-ink/10 text-[8px] font-semibold uppercase tracking-[0.18em] text-ink/40"><th className="px-6 py-4">Name</th><th className="px-6 py-4">Contact</th><th className="px-6 py-4">Service</th><th className="px-6 py-4">Project details</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Created</th></tr></thead><tbody className="divide-y divide-ink/10">{data.items.map((lead) => <tr key={lead.id} className="transition hover:bg-bone/45"><td className="px-6 py-5"><Link href={`/admin/leads/${lead.id}`} className="font-serif text-xl hover:text-bronze">{lead.customer_name ?? "Unassigned enquiry"}</Link></td><td className="px-6 py-5 text-xs leading-6 text-ink/55">{lead.email ?? "No email"}<br />{lead.phone ?? "No phone"}</td><td className="px-6 py-5 text-sm text-ink/60">{lead.service ?? "Not specified"}</td><td className="max-w-[250px] px-6 py-5 text-xs leading-5 text-ink/50">{lead.intent ?? "Requirements awaiting review."}</td><td className="px-6 py-5"><span className="bg-bone px-3 py-2 text-[8px] font-semibold uppercase tracking-[0.16em] text-ink/55">{lead.status}</span></td><td className="whitespace-nowrap px-6 py-5 text-xs text-ink/45">{formatDate(lead.created_at)}</td></tr>)}</tbody></table></div> : <div className="mt-8 border border-ink/10 bg-paper px-7 py-16 text-center"><p className="font-serif text-3xl">No leads yet.</p><p className="mt-3 text-sm text-ink/45">New enquiries will appear here.</p></div>}</div>;
}